## Arithmetic Functions

#### Addition

In [1]:
import numpy as np
var1=np.array([2,4,6,8])
var2=np.array([1,3,5,7])
varadd=np.add(var1,var2)
print(varadd)

[ 3  7 11 15]


#### Subtraction

In [ ]:
s1=np.array([1,5,8,9,2,4])
s2=np.array([2,6,3,8,1,4])
s_sub=np.subtract(s1,s2)
print(s_sub)
print("Dimension :",s_sub.ndim)



[-1 -1  5  1  1  0]
Dimension : 1


Multiply

In [12]:
m1=np.array([2,4,6])
m2=np.array([1,5,3])
# m2=np.array(4)
m_mult=np.multiply(m1,m2)
print(m_mult)
print("Dimension : ",m_mult.ndim)

[ 2 20 18]
Dimension :  1


Divide

In [20]:
d1=np.array([[2,4,6],[6,8,10]])
d2=np.array([[1,2,3],[3,4,5]])
div=np.divide(d1,d2)
print(div)
print("DImension : ",div.ndim)

[[2. 2. 2.]
 [2. 2. 2.]]
DImension :  2


Modulus


In [23]:
md1=np.array([5,9,17])
mod=np.mod(md1,3)
print(mod)


[2 0 2]


In [25]:
pw1=np.array([5,9,17])
power=np.power(pw1,2)
print(power)

[ 25  81 289]


In [27]:
r1=np.array([1,2,3],float)
r_p=np.reciprocal(r1)
print(r_p)

[1.         0.5        0.33333333]
