## ******** Array Operation *********

In [2]:
import numpy as np

### ARITHMETIC OPERATIONS 

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [6]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [7]:
ar1=a1-a2
ar1

array([-5, -5, -5, -5, -5])

In [8]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1%a2

array([1, 2, 3, 4, 5])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

### BROADCASTING 

In [14]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [15]:
arr+10

array([20, 30, 40, 50])

In [16]:
arr-5

array([ 5, 15, 25, 35])

In [17]:
arr*2

array([20, 40, 60, 80])

In [18]:
ar2=np.arange(0,25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ar2+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [20]:
ar2*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57],
       [60, 63, 66, 69, 72]])

### DEEP ans SHALLOW COPY 

In [21]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
sl=a[:5]
sl

array([1, 2, 3, 4, 5])

In [23]:
sl=sl+10
sl

array([11, 12, 13, 14, 15])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b[2]=90
b

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
c=a.copy()
c

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
c[1]=1010
c

array([   1, 1010,   90,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [33]:
a

array([ 1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### MATRIX OPERATIONS

In [34]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [37]:
A


array([[1, 2],
       [3, 4]])

In [38]:
B

array([[5, 6],
       [7, 8]])

In [40]:
cross=A*B
cross

array([[ 5, 12],
       [21, 32]])

In [41]:
div=A/B 
div

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [42]:
A@B

array([[19, 22],
       [43, 50]])

In [43]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [44]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [45]:
np.invert(A)

array([[-2, -3],
       [-4, -5]])

In [46]:
A.T

array([[1, 3],
       [2, 4]])

### STACKING ARRAY

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
B

array([[5, 6],
       [7, 8]])

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [53]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [57]:
np.row_stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### SPLITING ARRAY

In [61]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.split(c,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
np.split(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [71]:
np.vsplit(c,2)
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]