## ****** NUMPY ARRAY INDEXING ******

In [2]:
import numpy as np 

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

17

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [7]:
arr[1:10:2]

array([12, 14, 16, 18, 20])

In [8]:
arr[::]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

### ****** NUMPY INDEXING and SLICING OF MATRIX ******

In [11]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [14]:
arr[4]

array([25, 26, 27, 28, 29, 30])

In [23]:
arr[:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [24]:
arr[4,3]

28

In [27]:
arr[:2,1:3]

array([[2, 3],
       [8, 9]])

In [29]:
arr[:,2:3]

array([[ 3],
       [ 9],
       [15],
       [21],
       [27]])

In [30]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
arr[:,2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])