### Indexing in Numpy Array

In [12]:
import numpy as np

In [ ]:
arr=np.arange(15).reshape(3,5)
arr
print(arr[0,1:])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:


a=np.arange(10)
print(a)
s=slice(1,5)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]


In [24]:
import numpy as np
employees = np.array([
    [1, 25, 50000],  
    [2, 30, 60000], 
    [3, 28, 55000], 
    [4, 35, 65000], 
    [5, 40, 70000]   
])
print("Age of Employees from index 1:",employees[2:,1])
print("Salary of Employees from index 2:",employees[:,2])

Age of Employees from index 1: [28 35 40]
Salary of Employees from index 2: [50000 60000 55000 65000 70000]


In [40]:
arr2=np.arange(24).reshape(3,2,4)
print(arr2)
print("Sub Array1 :",arr2[0,:,1:3])
print("Sub Array2 :",arr2[:,1,:1])


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
Sub Array1 : [[1 2]
 [5 6]]
Sub Array2 : [[ 4]
 [12]
 [20]]
