### Iteration in Numpy Array

In [2]:
import numpy as np

# Example array
arr = np.array([[1, 2], [3, 4]])

# Iterate using nditer
for x in np.nditer(arr):
   print(x)

1
2
3
4


In [ ]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])
# Flat iteration using nditer with 'buffered' flag
print("Iterating over the array:")
for x in np.nditer(arr1, flags=['buffered']):
   print(x, end=' ')

Iterating over the array:
1 2 3 4 5 6 

In [ ]:
# Iterating Array With Different Data Types
arr2 = np.array([1, 2, 3])

for x in np.nditer(arr2, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
# Iterating With Different Step Size
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr3[:, ::2]):
  print(x)

1
3
5
7


In [11]:
arr4 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr4):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [13]:
# Create a 1D and a 2D array
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5, 6], [7, 8, 9]])

# Reshape array1 to make it 2D for concatenation along axis 0
array1_reshaped = array1.reshape(1, -1)
print("Reshaped Array:\n", array1_reshaped)

# Concatenate along axis 0
result = np.concatenate((array1_reshaped, array2), axis=0)

print("Concatenated Array:\n", result)

Reshaped Array:
 [[1 2 3]]
Concatenated Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
ar5=np.array([1,3,4,5,6])
arnew=np.array_split(ar5, 3)
print(arnew)
for i in arnew:
    print(i)


[array([1, 3]), array([4, 5]), array([6])]
[1 3]
[4 5]
[6]
