### JOINING & SPLITING 

In [1]:
import numpy as np


In [8]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[2,4,6,8],[1,3,5,7]])
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[1 2 3 4 2 4 6 8]
 [5 6 7 8 1 3 5 7]]


In [20]:
a1=np.arange(20).reshape((2,2,5))
a2=np.arange(20).reshape((2,2,5))
anew=np.stack((a1,a2),axis=1)
print(a1)
print(a2)
print()
print("Dimension of array is : ",anew.ndim)
print(anew)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Dimension of array is :  4
[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[ 0  1  2  3  4]
   [ 5  6  7  8  9]]]


 [[[10 11 12 13 14]
   [15 16 17 18 19]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]]]


In [24]:
a1=np.arange(10).reshape((2,5))
a2=np.arange(10).reshape((2,5))
anew=np.vstack((a1,a2))
print(a1)
print(a2)
print()
print("Dimension of array is : ",anew.ndim)
print(anew)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]

Dimension of array is :  2
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
