In [1]:
import numpy as np 
print("numpy")

numpy


In [2]:
x=np.array([2,3,4,5])
print(type(x))

<class 'numpy.ndarray'>


### Execution time of List and Array in Python

In [6]:
## LIST
%timeit [j**4 for j in range(1,9)]

510 ns ± 3.92 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
import numpy as np
%timeit np.arange(1,9)**4

1.36 μs ± 6.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Dimensions in Arrays

In [14]:
## 1-D Array
ar1=np.array([1,2,3,4])
print(ar1)
print("Dimensions of array :",ar1.ndim)

[1 2 3 4]
Dimensions of array : 1


In [15]:
## 2-D Array
ar2=np.array([[1,3,5],[2,4,6]])
print(ar2)
print("Dimensions of array :",ar2.ndim)

[[1 3 5]
 [2 4 6]]
Dimensions of array : 2


In [17]:
ar3=np.array([[[1,3,5,4],[2,4,6,8],[8,9,10,12]]])
print(ar3)
print("Dimensions of array :",ar3.ndim)

[[[ 1  3  5  4]
  [ 2  4  6  8]
  [ 8  9 10 12]]]
Dimensions of array : 3


In [19]:
## N-D Arrays
ar4=np.array([2,4,6,8],ndmin=8)
#ndim define the dimensions of the Array 
print(ar4)
print("Dimensions of the Array :",ar4.ndim)

[[[[[[[[2 4 6 8]]]]]]]]
Dimensions of the Array : 8


In [25]:
zero=np.zeros([2,4])
one=np.ones([4,3])
print(zero)
print(one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
ar_empty=np.empty((3,2))
print(ar_empty)

[[4.9e-324 1.5e-323]
 [2.5e-323 9.9e-324]
 [2.0e-323 3.0e-323]]
