### ************** NUMPY ARRAYS ****************** 

In [2]:
print("Numpy Arrays")

Numpy Arrays


In [3]:
import numpy as np 
print("Import Successfully")

Import Successfully


In [6]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
l=[1,3.4,'A',"hello",True]
print(l)

[1, 3.4, 'A', 'hello', True]


In [11]:
ar1=np.array(l)
ar1

array(['1', '3.4', 'A', 'hello', 'True'], dtype='<U32')

In [12]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **** ARRAY GENERATION FUNCTION *****

In [15]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
ar1=np.arange(1,11,2)
ar1

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
ar1=np.zeros((3,4))
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
ar2=np.ones((4,4))
ar2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
ar3=np.linspace(2,10,num=5)
ar3

array([ 2.,  4.,  6.,  8., 10.])

In [29]:
ar4=np.linspace(1,3,10)
ar4

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

### ****** RANDOM GENERATION FUNCTION ******

In [32]:
ar1=np.random.rand(5)
ar1

array([0.13219971, 0.22196132, 0.06840628, 0.28308663, 0.55481516])

In [34]:
ar2=np.random.rand(3,4)
ar2

array([[0.26490178, 0.71984818, 0.65500475, 0.6605772 ],
       [0.36646567, 0.73000508, 0.00337164, 0.42044128],
       [0.5815183 , 0.57671361, 0.68080478, 0.78874115]])

In [35]:
ar3=np.random.randn(10)
ar3

array([-0.07320669, -0.20046463,  0.55306465, -0.71741153, -1.85055547,
        1.33560836, -2.34491804, -0.62446115,  0.02720428, -0.87293991])

In [36]:
ar4=np.random.randint(5)
ar4

3

In [47]:
ar5=np.random.randint(10,30)
ar5

29

In [48]:
ar6=np.random.randint(5,30,10)
ar6

array([19,  5,  8, 25, 13, 29, 23, 21,  5, 15])

### ******** ARRAY ARRTRIBUTES ********

In [50]:
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ar1.shape

(3, 3)

In [53]:
ar1.size

9

In [54]:
ar1.dtype

dtype('int32')

### ********* ARRAY METHODS *********

In [55]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar1.min()

1

In [57]:
ar1.max()

9

In [58]:
ar1.sum()

45

In [60]:
print(ar1)
np.sum(ar1,axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [61]:
np.sum(ar1,axis=1)

array([ 6, 15, 24])

In [62]:
ar1.mean()

5.0

In [63]:
ar1.std()

2.581988897471611

In [64]:
ar1.argmax()

8

In [66]:
ar1.argmin()

0

### ********* RESHAPING and  RESIZING *********

In [75]:
arr=np.arange(30)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [79]:
arr=arr.reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [80]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])