## Data types in Numpy Array

In [1]:
import numpy as np 

In [2]:
x=np.array([2,4,6,8])
print("Data Type : ",x.dtype)

Data Type :  int64


In [ ]:
x1=np.array([2,4,6,8],dtype=np.int64)
print(x1)
%timeit (x1)
print("Data Type : ",x1.dtype)

[2 4 6 8]
28.9 ns ± 1.32 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
Data Type :  int64


In [9]:
x2=np.array([2,4,6,8,10],dtype="f")
y2=np.int64(x2)
print(x2)
print(y2)
print("Data Type : ",x2.dtype)
print("Data Type : ",y2.dtype)

[ 2.  4.  6.  8. 10.]
[ 2  4  6  8 10]
Data Type :  float32
Data Type :  int64


In [21]:
x3=np.array([1,2,3,4,5,6],dtype="m")
print(x3)
print("Data type : ",x3.dtype)

[1 2 3 4 5 6]
Data type :  timedelta64


In [23]:
x4=x3.astype("O")
print(x4)
print(x4.dtype)
x5=x4.astype("U")
print(x5)
print(x5.dtype)

[1 2 3 4 5 6]
object
['1' '2' '3' '4' '5' '6']
<U1
