## Numpy Arrays Using Functions

In [2]:
import numpy as np

#### 1. Array with Zeros

In [ ]:
ar_zero=np.zeros(3)
print(ar_zero)
print(type(ar_zero))

[0. 0. 0.]
<class 'numpy.ndarray'>


In [13]:
ar_z1=np.zeros([3,4])
# ar_z1=np.zeros((3,2,3))
print(ar_z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 2. Array with Ones 

In [22]:
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [23]:
ar_one1=np.ones(4,bool)
print(ar_one1)

[ True  True  True  True]


#### 3. Create an Empty Array

In [28]:
ar_emp=np.empty(5,int)
print(ar_emp)

[            0 2315573750224 2315573747264 2315573747184       7143424]


In [30]:
ar_em=np.empty([2,3])
print(ar_em)

[[6.23042070e-307 3.91299992e-321 0.00000000e+000]
 [1.14402009e-311 0.00000000e+000 7.56571287e-307]]


#### 4. Array with range  

In [35]:
ar_r=np.arange(1,12)
print(ar_r)

[ 1  2  3  4  5  6  7  8  9 10 11]


#### 5. Array with Diagonal Element fill with 1`s

In [54]:
ar_d=np.eye(3,4,2,int)
print(ar_d)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


#### 6. Array filled with Given Value

In [3]:
ar_g=np.full((3,4),6)
print(ar_g)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
