In [2]:
import numpy as np
print("Numpy import successfully")

Numpy import successfully


In [3]:
test=np.array([[100,200,300],[400,500,600],[700,800,900]])
print(test.ndim)
print(test.shape)
print(test.flatten())
print(np.diagonal(test))
print(np.max(test))
print(test[0:1])
print(test[0:1,0:1])
print(test[1][2])
print(np.mean(test))
print(np.sum(test))

2
(3, 3)
[100 200 300 400 500 600 700 800 900]
[100 500 900]
900
[[100 200 300]]
[[100]]
600
500.0
4500
