In [2]:
import numpy as np
print("Numpy import successfully")

Numpy import successfully


#### Dimension in Array

In [5]:
# 1-D array
x=[1,3,5,6,8]
print("Before array type: ",type(x))
x=np.array(x)
print("After array type: ",type(x))
print("Dimension: ",x.ndim)

Before array type:  <class 'list'>
After array type:  <class 'numpy.ndarray'>
Dimension:  1


In [7]:
#2-D Array
y=[[1,3,5,7],[2,4,6,8]]
y=np.array(y)
print(y)
print("Dimention :",y.ndim)

[[1 3 5 7]
 [2 4 6 8]]
Dimention : 2


In [10]:
#3-D Array
z=[[[1,2],[3,4]],[[5,6],[6,5]],[[2,1],[4,3]]]
z=np.array(z)
print(z)
print("Dimention: ",z.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 5]]

 [[2 1]
  [4 3]]]
Dimention:  3


In [3]:
test=np.array([[100,200,300],[400,500,600],[700,800,900]])
print(test.ndim)
print(test.shape)
print(test.flatten())
print(np.diagonal(test))
print(np.max(test))
print(test[0:1])
print(test[0:1,0:1])
print(test[1][2])
print(np.mean(test))
print(np.sum(test))

2
(3, 3)
[100 200 300 400 500 600 700 800 900]
[100 500 900]
900
[[100 200 300]]
[[100]]
600
500.0
4500
