In [1]:
import numpy as np
print("Numpy import successfully")

Numpy import successfully


### Valid Sudoku

In [2]:
s=np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [12]:
h=np.sum(s,axis=1)
h=h.sum()
h

405

In [13]:
v=np.sum(s,axis=0)
v=v.sum()
v

405

In [14]:
if(v==h):
    print("It is valid Sudoku")

It is valid Sudoku


In [16]:
a1=s[:3,:3]
a1.sum()


45

In [19]:
a2=s[:3,3:6]
a2
a2.sum()

45

In [21]:
a3=s[:3,6:]
a3
a3.sum()

45

In [ ]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])
        

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [25]:
for i in range(0,9,3):
    for j in range(0,9,3):
        a1=s[i:i+3,j:j+3]
        print(a1.sum())

45
45
45
45
45
45
45
45
45


#### General Question 

In [51]:
#Columns:[Age,math marks,science marks]
data=np.array([
    [18,85,78], #Student 1
    [19,92,88], #Student 2
    [17,76,95], #Student 3
    [18,65,70], #Student 4
    [20,90,85]  #Student 5
])

In [28]:
#Get the shape of matrix
data.shape

(5, 3)

In [32]:
# Find the average age of students
np.mean(data[:,0])

18.4

In [33]:
#Extract Math marks of all students
print("Maths marks")
data[:,1]

Maths marks


array([85, 92, 76, 65, 90])

In [38]:
#Find the highest math marks of all students
print("Highest marks",end=" ");print("of Students :")
np.max(data[:,1])


Highest marks of Students :


92

In [40]:
#get the details of student who scored more than 90 in math
i=data[:,1]>90
print(data[i])

[[19 92 88]]


In [58]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [59]:
#Increase math marks of all student by 5
data[:,1]+=5

In [60]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [61]:
#Calculate the avarage marks  in each subject(Column-wise)
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])