In [3]:
import numpy as np 

In [4]:
print(np.__version__)

1.26.4


    #### Execution time of LIST and Array

In [5]:
%timeit [j**4 for j in range(1,3)]

417 ns ± 26.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
%timeit np.arange(1,3)**4

3.01 μs ± 227 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


    #### Create the numpy array

In [8]:
arr = np.array([2,4,6,8])
print(arr)

[2 4 6 8]


In [9]:
# LIST in array
l=[1,3,5,7,9]
ar2=np.array(l)
print(ar2)

[1 3 5 7 9]


         Dimesions in Array

In [11]:
# 1-D array
x=[1,2,3,4,5]
x=np.array(x)
print(x.ndim)

1


In [12]:
# 2-D Array
y=[[1,2],[3,4]]
y=np.array(y)
print(y.ndim)

2


In [16]:
# N-D Array 
n=np.array([1,2,3],ndmin=10)
print(n.ndim)
print(n)

10
[[[[[[[[[[1 2 3]]]]]]]]]]


In [17]:
arr=np.zeros([2,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
arr2=np.ones((3,4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
arr3=np.empty((4,4))
print(arr3)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.12199579e-314]]


In [39]:
# Array with range 
arr4=np.arange(12)
arr4
arr4.reshape(3,4)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
arr= np.linspace(1,5,num=3)
arr

array([1., 3., 5.])

In [7]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

r=np.corrcoef(x,y)[0,0]
print("Pearson Correlation Coefficient: ",r)

Pearson Correlation Coefficient:  0.9999999999999999
